FROM node:22-alpine

ARG CLIENT_PORT=3000
ENV CLIENT_PORT=${CLIENT_PORT}

WORKDIR /app
COPY ./package.json .
COPY ./yarn.lock .
COPY ./next.config.ts .
COPY ./postcss.config.mjs .
COPY ./tailwind.config.ts .

COPY ./tsconfig.json .
COPY ./entrypoint.dev.sh ./entrypoint.sh

RUN chmod +x ./entrypoint.sh
RUN yarn

ENTRYPOINT [ "./entrypoint.sh" ]