import type { Metadata } from "next"
import "./globals.css"
import TopBar from "./TopBar"
import { DataProvider } from "./context/data"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>
                <DataProvider>
                    <TopBar />
                </DataProvider>
                {children}
            </body>
        </html>
    )
}
