# Build image
FROM python:3.13.5-bookworm AS builder

ARG POETRY_VERSION
RUN pip install poetry==${POETRY_VERSION}

WORKDIR /app
COPY pyproject.toml poetry.lock ./
# Poetry complains without a readme
RUN touch README.md
RUN poetry install --no-root

COPY src ./src
RUN poetry install

RUN mkdir /run/secrets
RUN echo "bbf" > /run/secrets/db_secret
RUN echo "eqoithqweighdeoihgeph" > /run/secrets/user_secret

ENTRYPOINT ["poetry", "run", "python", "src/api/main.py"]