name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild the docker image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd ${{ vars.PROJECT_ROOT }}
            git pull
            docker compose -f docker-compose.prod.yml up --build -d
            psql \
              -h ${{ vars.DB_HOST }} \
              -d ${{ vars.DB_NAME }} \
              -U ${{ vars.DB_USER }} \
              -a \
              -f db/scripts/1_types.sql
            psql \
              -h ${{ vars.DB_HOST }} \
              -d ${{ vars.DB_NAME }} \
              -U ${{ vars.DB_USER }} \
              -a \
              -f db/scripts/2_functions.sql
